<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOeprnvk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOeprnvk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOeprnvk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOeprnvk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOeprnvk\appProdProjectContainer([
    'container.build_hash' => 'Oeprnvk',
    'container.build_id' => 'adf77ffd',
    'container.build_time' => 1610452241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOeprnvk');
